import numpy as np
# The ACTUAL Antihydra map c->floor(3c/2) on Z_2 has the 2-adic SHIFT (mixing), unlike pure (3/2)^n.
# Model the low-k bits as a Markov chain: state = c mod 2^k. Step: c' = floor(3c/2); the bit shifted IN
# (bit k of c, the "fresh" high bit) is modeled UNIFORM (it is generated by the x3 high part).
# Build the transition operator on Z/2^k and measure its SPECTRAL GAP. A gap => low bits mix exponentially.
for k in (6,8,10):
    K=1<<k
    P=np.zeros((K,K))
    for s in range(K):           # s = c mod 2^k
        for hb in (0,1):         # fresh incoming high bit (bit k), modeled uniform
            c = s + (hb<<k)      # lift to mod 2^{k+1}
            cp = (3*c)//2         # floor(3c/2)
            P[s, cp % K] += 0.5
    # stationary + spectral gap
    ev=sorted(np.linalg.eigvals(P.T), key=lambda z:-abs(z))
    lam2=abs(ev[1])
    print(f"k={k:2d} (Z/2^{k}): |lambda_1|={abs(ev[0]):.4f} |lambda_2|={lam2:.4f}  spectral gap={1-lam2:.4f}")
    if k==8:
        # check stationary is uniform (=> even-density 1/2)
        w,v=np.linalg.eig(P.T)
        i=np.argmin(np.abs(w-1))
        stat=np.real(v[:,i]); stat/=stat.sum()
        print(f"      stationary dist: min={stat.min():.5f} max={stat.max():.5f} (uniform=1/{K}={1/K:.5f})")
        evendens=sum(stat[s] for s in range(K) if s%2==0)
        print(f"      => even-density under stationary = {evendens:.5f} (need >1/3)")
print("\n=> if gap>0 uniformly in k, the low-bit Markov chain MIXES: parity -> fair coin, depth=o(n).")
print("   The remaining gap: justifying 'incoming high bit ~ uniform' = the high-bit equidistribution.")
