#!/usr/bin/env python3
"""x2fr_analyze.py -- analyze the recursive structure of the chew-start sequence.

Extract the full (blk,comb) chew-start sequence, save it, and probe its
self-similar / odometer structure:
  - the sub-blocks between successive "big reads" (main cascade descents)
  - whether the sequence is generated by a mixed-radix odometer recursion
"""
import sys, pickle
sys.path.insert(0, '/Users/aokiyousuke/busybeaver')
from x2bd_sim import build
from x2bd_outer import run, chew_starts


def extract(g):
    anchors = run(g)
    starts, pts = chew_starts(anchors)
    return [(blk, comb) for (n, blk, comb, ones, pos) in starts]


if __name__ == "__main__":
    g = int(sys.argv[1]) if len(sys.argv) > 1 else 2
    seq = extract(g)
    with open(f'/private/tmp/claude-502/-Users-aokiyousuke-busybeaver/8b7a3f39-ce4e-4044-afe8-60ce3b3aedcf/scratchpad/seq_g{g}.pkl','wb') as f:
        pickle.dump(seq, f)
    print(f"g={g} K={g+8}: {len(seq)} chew-starts saved")
    # Print the FULL sequence of blk values only, so we can see the recursion
    blks = [b for b,_ in seq]
    combs = [c for _,c in seq]
    # print positions where comb>0 (the carries) with their index
    carries = [(i, blks[i], combs[i]) for i in range(len(seq)) if combs[i] > 0]
    print(f"# events with comb>0 (carry-triggers): {len(carries)}")
    print("first 40 carry-triggers (idx, blk, comb):")
    for x in carries[:40]:
        print("  ", x)
    # the comb value at a carry = 2^j - 1?
    from collections import Counter
    print("comb-value distribution at carries:", dict(sorted(Counter(c for _,_,c in carries).items())))
    # blk at carry distribution
    print("blk-value distribution at carries:", dict(sorted(Counter(b for _,b,_ in carries).items())))
