name = "runstructure"
version = "0.1.0"
defaultTargets = ["RunStructure", "Template", "Suffix", "O3", "Mirror", "O18", "O2", "O17"]

[[lean_lib]]
name = "RunStructure"

[[lean_lib]]
name = "Mirror"

[[lean_lib]]
name = "Template"

[[lean_lib]]
name = "Suffix"

[[lean_lib]]
name = "O3"

[[lean_lib]]
name = "O18"

[[lean_lib]]
name = "O2"

[[lean_lib]]
name = "O17"
