name = "runstructure"
version = "0.1.0"
defaultTargets = ["RunStructure", "Template", "Suffix", "O3"]

[[lean_lib]]
name = "RunStructure"

[[lean_lib]]
name = "Template"

[[lean_lib]]
name = "Suffix"

[[lean_lib]]
name = "O3"
